CREATE DATABASE SISTEMA_INVENTARIO;
USE SISTEMA_INVENTARIO;
CREATE TABLE USUARIOS(
    ID INT(11) NOT NULL,
    USUARIO VARCHAR (15) NOT NULL,
    CONTRASEÑA VARCHAR (20) NOT NULL,
    NOMBRE_COMPLETO VARCHAR (100) NOT NULL
);
ALTER TABLE USUARIOS 
        ADD PRIMARY KEY (ID);
        ALTER TABLE USUARIOS
        MODIFY ID INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
        DESCRIBE USUARIOS;



        -- INVENTARIO
        CREATE TABLE LISTA_MAQUINAS(
            ID INT(11) NOT NULL,
            EQUIPO VARCHAR (100) NOT NULL,
            CANTIDAD INT (5) NOT NULL,
            MARCA VARCHAR(100) NOT NULL,
            MODELO VARCHAR(100) NOT NULL,
            FUNCIONAMIENTO TEXT,
            OBSERVACIONES TEXT,
            USER_ID INT(11),
            CREATE_AT timestamp NOT NULL DEFAULT current_timestamp,
        CONSTRAINT fk_USUARIO FOREIGN  KEY (USER_ID) REFERENCES USUARIOS(ID)
        );
        ALTER TABLE LISTA_MAQUINAS
            ADD PRIMARY KEY (ID);

        ALTER TABLE LISTA_MAQUINAS
            MODIFY ID INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;